### PR TITLE
Convert all commands from the Fun category to slash commands

### PR DESCRIPTION
**Pull request by RayTracerGC**

### CODE REVIEW

**Review by fungusdesu — CHANGES_REQUESTED** [review]
no need for deprecation warning, i have already implemented an automated deprecation message in messageCreate.js, please edit your code accordingly

**Comment by RayTracerGC** [comment]
Removed deprecation warnings for prefix commands from the fun category

**Review by fungusdesu — CHANGES_REQUESTED** [review]
please do not remove the commands. we will need to keep it until everything is converted, for now please still keep the normal prefix commands, dont delete them

**Comment by RayTracerGC** [comment]
Restored the -prefix commands from the fun category

**Comment by RayTracerGC** [comment]
I will redo this later because I need to sync my fork with your repo

**Pull request closed without merging**
